name: flutter_opacity_core
description: "Opacity Core for flutter"
version: 0.0.1
homepage: https://opacity.network
repository: https://github.com/OpacityLabs/flutter-opacity-core

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.opacitylabs.flutter_opacity_core
        pluginClass: FlutterOpacityCorePlugin
      ios:
        pluginClass: FlutterOpacityCorePlugin
