name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    permissions:
      id-token: write
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: "3.24.4"
      - uses: flutter-actions/setup-pubdev-credentials@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Update pubspec.yaml version
        run: |
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          sed -i "s/^version:.*/version: $tag/" pubspec.yaml
      - name: Publish
        run: flutter pub publish --force
      - name: Create Github Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
