name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install Latest Stable Flutter
        run: |
          # Download and install the latest stable Flutter version
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version  # Confirm installed Flutter version and Dart SDK

      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Update pubspec.yaml version
        run: |
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          sed -i "s/^version:.*/version: $tag/" pubspec.yaml
      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
